// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTgyzLv4c-bWnT8Ml8rtw6ZMixqVg_2qI',
    appId: '1:22261468756:web:4aa2f3f39f6c49e19ea7c1',
    messagingSenderId: '22261468756',
    projectId: 'moviesapp-project-77637',
    authDomain: 'moviesapp-project-77637.firebaseapp.com',
    storageBucket: 'moviesapp-project-77637.firebasestorage.app',
    measurementId: 'G-Y8011F9SWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Co75XP_MojSnWzQ4FmaS9M4l3K06lEs',
    appId: '1:22261468756:android:9cf8564b61942d359ea7c1',
    messagingSenderId: '22261468756',
    projectId: 'moviesapp-project-77637',
    storageBucket: 'moviesapp-project-77637.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwvPv0EW-ZtrXbDFZ0NYaTKGLW4VY-KvA',
    appId: '1:22261468756:ios:28ee221233d770d09ea7c1',
    messagingSenderId: '22261468756',
    projectId: 'moviesapp-project-77637',
    storageBucket: 'moviesapp-project-77637.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwvPv0EW-ZtrXbDFZ0NYaTKGLW4VY-KvA',
    appId: '1:22261468756:ios:28ee221233d770d09ea7c1',
    messagingSenderId: '22261468756',
    projectId: 'moviesapp-project-77637',
    storageBucket: 'moviesapp-project-77637.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTgyzLv4c-bWnT8Ml8rtw6ZMixqVg_2qI',
    appId: '1:22261468756:web:baa7b86c525561159ea7c1',
    messagingSenderId: '22261468756',
    projectId: 'moviesapp-project-77637',
    authDomain: 'moviesapp-project-77637.firebaseapp.com',
    storageBucket: 'moviesapp-project-77637.firebasestorage.app',
    measurementId: 'G-CFQ0F9743W',
  );
}
